# Generated by Django 3.1.2 on 2021-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='location_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
