# Generated by Django 3.1.2 on 2021-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210608_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='product_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
